// Personalized phrase pool: real one-liners from your school teachers,
// pulled from the "Hlody" column of a few recent Gilotina issues.
const PHRASES = [
  "Žeru děti jenom v sobotu a neděli, jinak za mnou můžete přijít.",
  "Při prudké změně nadmořské výšky v letadle vás začnou hrozně bolet uši.",
  "Podívejte na něho. Fyzik a neumí fyziku.",
  "Ten chromozom vypadá jak totální žebrák!",
  "Jak je možné, že když jsem se před deseti minutama díval, tak bylo 14:27 a teď je 14:28?",
  "To přijdeš k takovému domu, který má na sobě nápis „Řeznictví“.",
  "Když si ti z vás, kteří chtějí být klasifikováni ze ZSV, dělají zápis, přemýšlíte o tvaru jednotlivých písmenek?",
  "Kdo to nechápe, může si sbalit věci a podívat se, jak mu to jezdí na Křenovou.",
  "Děcka, vy potřebujete jít domů. Ne, já potřebuju jít domů.",
  "Některým žákům nemusím říkat, že si mají zapisovat moje moudrá slova.",
  "Kdo nebude vědět, jak to spočítat, požádá souseda, aby mu jednu vrazil.",
  "Ty máš kontinuální, 365denní státní svátek!",
  "Ani sešit nemá! Ty sem chodíš jen na besídku!",
  "I lichá čísla mají právo na život!",
  "Počátek. To je buď narození Ježíše, nebo bod nula nula.",
  "Prosím vás, zdrojem omega 3 kyselin není ořechovice!",
  "Mozkomíšní mok je voda, která tlumí názory.",
  "Kdo vymyslel učebnu, která je do kopce?!",
  "Kdo bude listovat zpátky, zaplatí kilo. Do fondu Máme rádi Police.",
  "Co to má jako být?! To by nenapsali ani v Pardubicích!",
  "Mám pocit, že poslední dobou tady děláte kulový.",
  "Až si tady vyrazím zuby, tak tě budu žalovat za újmu na zdraví!",
  "Kdo mi do písemky napíše „uhlovodany“, toho přinutím tu písemku pozřít.",
  "Milý pane profesore.",
  "Do you want subtitles in Czech or in English?",
  "Kopni do něj.",
  "To nevadí. Že ti nevadí, že na tebe mluvím, i když tady nejsi?",
  "Ježíšmarja, kde to jsem?!",
  "To je taková ta bílá bichle, ze které se učil už Ježíš.",
  "Odpovídá mi někdo, nebo se teď všichni bavíte o něčem jiném?",
  "Znám i takové týpky, pro které známky motivace nejsou. Co s nimi mám dělat?",
  "Za chvilku budu mít přirozenou motivaci naběhnout k lavici tam vzadu u okna.",
  "Ten, kdo ještě pracuje, se přece nemá čas hlásit!",
  "X, z tebe něco teče.",
  "Kafe jsem ráno měla, nevím, co se se mnou děje.",
  "Ale ty seš těžkej.",
  "Jaký „nemám tucha“?! Já ti urvu ucha!",
  "Opřete se, čas na poezii.",
  "Názvosloví je opět úplně blbuvzdorné.",
  "Slzný plyn, jak ho, holky, znáte? Nosíte ho v kabelkách?",
  "Děcka, ale to fakt není sranda, tam vymřelo tak milion lidí.",
  "Vypadá to, že tvoje IQ se bude za chvíli rovnat dnešnímu datu!",
  "A nechceš ještě polštář?",
  "Kdyby byla lenost jednotka, tak bys to byl ty!",
  "Nikdo si nemůže být jistý, čeho je Homo studients schopný.",
  "Není tam žádný diesel agregát, který by tam ten vzduch vháněl.",
  "Nebudete dělat blbosti a stříhat si tady chrpy!",
  "Tím známým časopisem, Gilotinou, byl popravenej a dvacet vteřin mrkal, fakt jo.",
];

function randomPhrase() {
  return PHRASES[Math.floor(Math.random() * PHRASES.length)];
}

module.exports = { PHRASES, randomPhrase };
